# validate
# cat .codecov.yml | curl --data-binary @- https://codecov.io/validate

codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        if_ci_failed: error #success, failure, error, ignore
        informational: true
        only_pulls: true

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

ignore:
  - "config/**/*"
  - "pkg/apis/**/*"
  - "mocks/**/*"
  - "integration/shared/scenarios/**/*"
  - "pkg/common/logger.go"
  - "test/*"
