linters-settings:
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3
  govet:
    check-shadowing: true
  nolintlint:
    require-explanation: true
    require-specific: true

linters:
  enable:
    - dupl
    - goconst
    - gocritic
    - gofmt
    - goimports
    - misspell
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go # disable some linters on test files
      linters:
        - dupl

run:
  issues-exit-code: 1
  concurrency: 4
  skip:
    - .*_mock.go
    - mocks/
    - pkg/apis/
