site_name: AWS Cloud Map MCS Controller
repo_name: aws/aws-cloud-map-mcs-controller-for-k8s
repo_url: https://github.com/aws/aws-cloud-map-mcs-controller-for-k8s

plugins:
  - search
theme:
  name: material
  language: en
  favicon: images/cloudmap.svg
  logo: images/cloudmap.svg

