
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - multicluster.k8s.aws
  resources:
  - serviceexports
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - multicluster.k8s.aws
  resources:
  - serviceexports/finalizers
  verbs:
  - get
  - update
- apiGroups:
  - multicluster.k8s.aws
  resources:
  - serviceimports
  verbs:
  - get
  - list
  - patch
  - update
