# An example object of `id.k8s.io ClusterProperty` 
# using a kube-system ns uuid as the id value:

apiVersion: about.k8s.io/v1alpha1
kind: ClusterProperty
metadata:
  name: id.k8s.io
spec:
  value: sample-mcs-clusterid
