apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: $CLUSTER_NAME
  region: $AWS_REGION
  version: "1.21"
vpc:
  cidr: $VPC_CIDR
  autoAllocateIPv6: false
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
managedNodeGroups:
- name: $NODEGROUP_NAME
  instanceType: t2.small
  minSize: 1
  maxSize: 10
  desiredCapacity: 1