# An example object of `cluster.clusterset.k8s.io ClusterProperty`

apiVersion: about.k8s.io/v1alpha1
kind: ClusterProperty
metadata:
  name: cluster.clusterset.k8s.io
spec:
  value: sample-mcs-clusterid
---
# An example object of `clusterset.k8s.io ClusterProperty`:

apiVersion: about.k8s.io/v1alpha1
kind: ClusterProperty
metadata:
  name: clusterset.k8s.io
spec:
  value: sample-mcs-clustersetid
