#!/usr/bin/env bash

export KIND_BIN='./bin/kind'
export KUBECTL_BIN='kubectl'
export LOGS='./integration/kind-test/testlog'
export KIND_CONFIGS='./integration/kind-test/configs'
export SHARED_CONFIGS='./integration/shared/configs'
export SCENARIOS='./integration/shared/scenarios'
export NAMESPACE='aws-cloud-map-mcs-e2e'
export ENDPT_PORT=80
export SERVICE_PORT=8080
export CLUSTERIP_SERVICE='e2e-service'
export HEADLESS_SERVICE='e2e-headless'
export KIND_SHORT='cloud-map-e2e'
export CLUSTER='kind-cloud-map-e2e'
export CLUSTERID1='kind-e2e-clusterid-1'
export CLUSTERSETID1='kind-e2e-clustersetid-1'
export DNS_POD='client-hello'
export IMAGE='kindest/node:v1.21.12@sha256:f316b33dd88f8196379f38feb80545ef3ed44d9197dca1bfd48bcb1583210207'
export EXPECTED_ENDPOINT_COUNT=5
export UPDATED_ENDPOINT_COUNT=6
