# e2e-service-one.yaml
kind: Service
apiVersion: v1
metadata:
  namespace: aws-cloudmap-mcs-e2e
  name: e2e-service-one
spec:
  selector:
    app: nginx
  ports:
    - port: 8080
      targetPort: 80
