apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: aws-cloud-map-mcs-e2e
  name: coredns-deployment
  labels:
    app: coredns
spec:
  replicas: 5
  selector:
    matchLabels:
      app: coredns
  template:
    metadata:
      labels:
        app: coredns
    spec:
      containers:
        - name: coredns
          image: k8s.gcr.io/coredns:1.7.0
          ports:
            - containerPort: 80
