apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: aws-cloud-map-mcs-e2e
  name: nginx-hello-deployment
  labels:
    app: nginx-hello
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-hello
  template:
    metadata:
      labels:
        app: nginx-hello
    spec:
      containers:
        - name: nginx-hello
          image: nginxdemos/hello:0.3-plain-text
          ports:
            - containerPort: 80
