kind: Service
apiVersion: v1
metadata:
  namespace: aws-cloud-map-mcs-e2e
  name: e2e-clusterset-ip-service
spec:
  selector:
    app: nginx-hello
  ports:
    - port: 80
---
kind: ServiceExport
apiVersion: multicluster.x-k8s.io/v1alpha1
metadata:
  namespace: aws-cloud-map-mcs-e2e
  name: e2e-clusterset-ip-service
