name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '33 14 * * *'
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: aws/aws-cloud-map-mcs-controller-for-k8s/coredns-multicluster


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Tag image for github container repository with commit SHA
        run: 'docker pull runakash/coredns-arm64:v1.8.6'
      - name: Tag image for github container repository with commit SHA
        run: 'docker pull runakash/coredns-arm:v1.8.6'
      - name: Tag image for github container repository with commit SHA
        run: 'docker pull runakash/coredns-amd64:v1.8.6'
      - name: Tag image for github container repository with commit SHA
        run: 'docker pull runakash/coredns:v1.8.6'
      
      - name: Tag image for github container repository with commit SHA
        run: 'docker tag runakash/coredns-arm64:v1.8.6 ghcr.io/aws/aws-cloud-map-mcs-controller-for-k8s/coredns-multicluster/coredns-arm64:v1.8.6'   
      - name: Tag image for github container repository with commit SHA  
        run: 'docker tag runakash/coredns-arm:v1.8.6 ghcr.io/aws/aws-cloud-map-mcs-controller-for-k8s/coredns-multicluster/coredns-arm:v1.8.6'   
      - name: Tag image for github container repository with commit SHA  
        run: 'docker tag runakash/coredns-amd64:v1.8.6 ghcr.io/aws/aws-cloud-map-mcs-controller-for-k8s/coredns-multicluster/coredns-amd64:v1.8.6'   
      - name: Tag image for github container repository with commit SHA  
        run: 'docker tag runakash/coredns-amd64:v1.8.6 ghcr.io/aws/aws-cloud-map-mcs-controller-for-k8s/coredns-multicluster/coredns:v1.8.6'   
         
      - name: Push
        run: 'docker push ghcr.io/aws/aws-cloud-map-mcs-controller-for-k8s/coredns-multicluster/coredns:v1.8.6'
      - name: Push
        run: 'docker push ghcr.io/aws/aws-cloud-map-mcs-controller-for-k8s/coredns-multicluster/coredns-arm64:v1.8.6'
      - name: Push
        run: 'docker push ghcr.io/aws/aws-cloud-map-mcs-controller-for-k8s/coredns-multicluster/coredns-arm:v1.8.6'
      - name: Push
        run: 'docker push ghcr.io/aws/aws-cloud-map-mcs-controller-for-k8s/coredns-multicluster/coredns-amd64:v1.8.6'
