name: integration-test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration-test:
    name: Run Integration- Test
    runs-on: ubuntu-latest
    environment: Integration Test
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Set up env
        run: source ~/.bashrc
      - name: Start clean
        run: make integration-cleanup
      - name: Set up cluster
        run: make integration-setup
      - name: Run tests
        run: make integration-run
      - name: Clean up clusters
        run: make integration-cleanup